### PR TITLE
shortcut-fe: rework netfilter conntrack notification

### PR DESCRIPTION
**Pull request by AmadeusGhost**
The original patch over rode the nf_conntrack_un/register_notifier API, which will
break other modules relying on the API. Reworked the notification APIs to play nice
with others. Also avoid to touch the code of fullcone nat.

### CODE REVIEW

**Comment by Lrvineshaw** [comment]
这个东西一直和ssr有冲突，我基本都不编译了

**Comment by hxlls** [comment]
> 这个东西一直和ssr有冲突，我基本都不编译了

SFE没冲突把，我一直开着也没事，flow offload 倒是和端口转发有冲突

**Comment by black-cerberon** [comment]
Why you removed init.d script?

**Comment by AmadeusGhost** [comment]
@black-cerberon The init.d here is duplicated with luci-app-sfe, so I removed it.

**Comment by black-cerberon** [comment]
@AmadeusGhost this is compatible with mainstream Openwrt w/o luci-app-sfe? I use old init.d script for it.

**Pull request merged**
