### PR TITLE
Add device support: Surfilter Net110 Marvell 88F6281 based on LCE's patch

### PR DESCRIPTION
**Pull request by TonyTeng22**
Q：你知道这是`pull request`吗？(使用 "x" 选择)
* [x] 我知道

Changes:
1. add helloworld repo
2. add support device Surfilter Net110
3. add sample .config for device Surfilter Net110
4. add build uImage for Kirkwood

Hwinfo:
CPU: Feroceon 88FR131 Marwell 88F6281 ARMv5TE 1.2Ghz
RAM: 512MB (256MB + 256MB)
NAND: Samsung NAND 128MiB
SWITCH: Marvell 88E6171
PORT: 5  Gbps 
Mini-Pcie: 1 half-size
SATA: 2 SATA
USB:  1 USB2
Other:  console , SDHCI/MMC , Reset

### CODE REVIEW

**Comment by AmadeusGhost** [comment]
> 1. add helloworld repo

Why？

**Comment by TonyTeng22** [comment]
> > 1. add helloworld repo
> 
> Why？

Hi AmadeusGhost,
Thank you for the question.
"1. add helloworld repo" for new users to use the SSR plus more friendly. If this point is not allowed here, I will remove is asap and say sorry for my ignorance.

**Comment by AmadeusGhost** [comment]
Please remove changes to these two files:
pr

**Comment by TonyTeng22** [comment]
OK I will change what you told very soon and make a new PR . Tks

**Pull request closed without merging**
