### PR TITLE
target: add phytium support

### PR DESCRIPTION
**Pull request by Ailick**
Add new ARM64 device support for phytium.
For more information please visit : [https://www.phytium.com.cn/en/index/](url)
Test platform: THTF ChaoXiang TF830-V050
You can find it on some websites here :
[https://www.alibaba.com/product-detail/Tsinghua-Tongfang-Chaoxiang-TF830-V050-1_1600866902984.html](url)
[https://product.suning.com/0000000000/12413827808.html](url)
**Hardware information :**
CPU : FT-D2000/8 Eight-Core ARM64 2.30Ghz
More details :
[https://www.tomshardware.com/news/phytium-d2000-eight-core-for-desktops](url)
[https://chipsandcheese.com/2022/09/29/chinas-phytium-d2000-building-on-a72/](url)
GPU : AMD RX550 2GB
Memory : 16GB DDR4 3200Mhz
HDA : FT-HDA ( Soc integration )

### CODE REVIEW

**Comment by Ailick** [comment]
Image_1705541076607

**Comment by aiamadeus** [comment]
image
rtl wifi 删掉，不用这个

**Comment by Ailick** [comment]
> image rtl wifi 删掉，不用这个

顺便改了一下，一些不对劲的东西

**Comment by aiamadeus** [comment]
image
i2c 这边的缩进乱了

**Pull request merged**
