### PR TITLE
rockchip: Add support for NanoPi R2C

### PR DESCRIPTION
**Pull request by KLT007**
Q：你知道这是`pull request`吗？(使用 "x" 选择)
* [ yes] 我知道

Tested and compiled kernel can support R2S and R2C at the same time.
 target/linux/rockchip/patches-5.4 patches-5.10 There will be 4 more patches, numbered 810-813
In addition, target/linux/rockchip/armv8/config-* added a new line to enable phy driver configuration

target/linux/rockchip/armv8/config-5.10       |   1 +
 target/linux/rockchip/armv8/config-5.4        |   1 +
 ...r-fixed-Add-support-for-off-on-delay.patch |  27 +
 ...Add-driver-for-Motorcomm-YT85xx-PHYs.patch | 472 ++++++++++++++++++
 ...-phy_find_first-for-invalid-phy_addr.patch |  32 ++
 ...m64-dts-rockchip-Add-support-for-R2C.patch |  77 +++
 ...r-fixed-Add-support-for-off-on-delay.patch |  42 ++
 ...Add-driver-for-Motorcomm-YT85xx-PHYs.patch | 472 ++++++++++++++++++
 ...-phy_find_first-for-invalid-phy_addr.patch |  32 ++
 ...m64-dts-rockchip-Add-support-for-R2C.patch |  77 +++

### CODE REVIEW

**Comment by AmadeusGhost** [comment]
？不要直接改 r2s 的 dts，另外建个 r2c

**Comment by KLT007** [comment]
> ？不要直接改r2s的dts，另外建个r2c

R2C和R2S差异较小，所以没有新增一个设备，理论上直接编译R2S就能兼容2者

**Comment by ricksuzade-maker** [comment]
两者之间区别就是网卡芯片

**Comment by ricksuzade-maker** [comment]
两者之间区别就是网卡芯片

**Comment by AmadeusGhost** [comment]
https://github.com/immortalwrt/immortalwrt/commit/d9cb05957d6454f85285715162781e27f22b329e 像天灵大佬这样搞不是更好嘛🌚

**Comment by KLT007** [comment]
> [immortalwrt/immortalwrt@d9cb059](https://github.com/immortalwrt/immortalwrt/commit/d9cb05957d6454f85285715162781e27f22b329e) 像天灵大佬这样搞不是更好嘛

photo_2021-08-18_13-22-14

**Comment by Beginner-Go** [comment]
直接pick 天灵dalao的吧 整那么多commit干嘛

**Comment by lone-wind** [comment]
R2S和R2C的区别就在于更换了eth0网卡吧，既然没有大的区别，直接使用一个不是来得简单？若友善后续更换eth1推出R2X，是不是还得再加？编译一个固件，适用于3个设备，怎么想都简单

**Comment by KLT007** [comment]
in order to partition r2c and
r2c, decided to use immortalwrt/immortalwrt@d9cb059 Thank you very much for your comments

**Pull request closed without merging**
