### PR TITLE
kernel: bump 5.10 to 5.10.107

### PR DESCRIPTION
**Pull request by Beginner-Go**

### CODE REVIEW

**Comment by breakings** [comment]
不同步这个补丁肯定得炸 https://raw.githubusercontent.com/openwrt/openwrt/master/target/linux/generic/hack-5.10/220-arm-gc_sections.patch

**Comment by mitsukileung** [comment]
的确炸了
Applying /workdir/openwrt/target/linux/generic/hack-5.10/220-gc_sections.patch using plaintext: 
patching file arch/arm/Kconfig
patching file arch/arm/boot/compressed/Makefile
patching file arch/arm/kernel/vmlinux.lds.S
patching file arch/arm/include/asm/vmlinux.lds.h
Hunk #1 FAILED at 23.
Hunk #2 succeeded at 109 (offset 13 lines).
Hunk #3 FAILED at 112.
2 out of 3 hunks FAILED -- saving rejects to file arch/arm/include/asm/vmlinux.lds.h.rej
Patch failed!  Please fix /workdir/openwrt/target/linux/generic/hack-5.10/220-gc_sections.patch!
make[3]: Leaving directory '/workdir/openwrt/toolchain/kernel-headers'
time: toolchain/kernel-headers/compile#10.86#5.12#12.92
make[3]: *** [Makefile:123: /workdir/openwrt/build_dir/toolchain-aarch64_cortex-a53_gcc-8.4.0_musl/linux-5.10.106/.prepared] Error 1
    ERROR: toolchain/kernel-headers failed to build.
make[2]: Leaving directory '/workdir/openwrt'
make[2]: *** [toolchain/Makefile:97: toolchain/kernel-headers/compile] Error 1
make[1]: *** [toolchain/Makefile:93: /workdir/openwrt/staging_dir/toolchain-aarch64_cortex-a53_gcc-8.4.0_musl/stamp/.toolchain_compile] Error 2
make[1]: Leaving directory '/workdir/openwrt'
make: *** [/workdir/openwrt/include/toplevel.mk:230: world] Error 2
Error: Process completed with exit code 2.

**Comment by Boos4721** [comment]
> 不同步这个补丁肯定得炸 [openwrt/openwrt@`master`/target/linux/generic/hack-5.10/220-arm-gc_sections.patch (raw)](https://raw.githubusercontent.com/openwrt/openwrt/master/target/linux/generic/hack-5.10/220-arm-gc_sections.patch)

NA, WORKS
iShot2022-03-20 20 30 18

**Comment by 1054009064** [comment]
> 

您的库在 5.10.105 就更新这个补丁了，能工作也正常

**Comment by 1054009064** [comment]
> > 不同步这个补丁肯定得炸 [openwrt/openwrt@`master`/target/linux/generic/hack-5.10/220-arm-gc_sections.patch (raw)](https://raw.githubusercontent.com/openwrt/openwrt/master/target/linux/generic/hack-5.10/220-arm-gc_sections.patch)
> 
> NA, WORKS iShot2022-03-20 20 30 18

您的库在 5.10.105 就更新这个补丁了，能工作也正常

**Comment by Beginner-Go** [comment]
> 的确炸了 Applying /workdir/openwrt/target/linux/generic/hack-5.10/220-gc_sections.patch using plaintext: patching file arch/arm/Kconfig patching file arch/arm/boot/compressed/Makefile patching file arch/arm/kernel/vmlinux.lds.S patching file arch/arm/include/asm/vmlinux.lds.h Hunk #1 FAILED at 23. Hunk #2 succeeded at 109 (offset 13 lines). Hunk #3 FAILED at 112. 2 out of 3 hunks FAILED -- saving rejects to file arch/arm/include/asm/vmlinux.lds.h.rej Patch failed! Please fix /workdir/openwrt/target/linux/generic/hack-5.10/220-gc_sections.patch! make[3]: Leaving directory '/workdir/openwrt/toolchain/kernel-headers' time: toolchain/kernel-headers/compile#10.86#5.12#12.92 make[3]: *** [Makefile:123: /workdir/openwrt/build_dir/toolchain-aarch64_cortex-a53_gcc-8.4.0_musl/linux-5.10.106/.prepared] Error 1 ERROR: toolchain/kernel-headers failed to build. make[2]: Leaving directory '/workdir/openwrt' make[2]: *** [toolchain/Makefile:97: toolchain/kernel-headers/compile] Error 1 make[1]: *** [toolchain/Makefile:93: /workdir/openwrt/staging_dir/toolchain-aarch64_cortex-a53_gcc-8.4.0_musl/stamp/.toolchain_compile] Error 2 make[1]: Leaving directory '/workdir/openwrt' make: *** [/workdir/openwrt/include/toplevel.mk:230: world] Error 2 Error: Process completed with exit code 2.

修好了

**Pull request merged**
