### PR TITLE
kernel: bump 5.10 to 5.10.85

### PR DESCRIPTION
**Pull request by Boos4721**
Signed-off-by: boos4721 <3.1415926535boos@gmail.com>

### CODE REVIEW

**Comment by BKPepe** [comment]
Do you have any plans to push it upstream? I can see that in OpenWrt, there is a 5.10.83 version. It would be nice to have it there as well.

I see there is a pending pull request for it:
https://github.com/openwrt/openwrt/pull/4811/files

Can you add there your  ``Tested-by`` and on which platform(s) did you compile it and run tested it?

**Comment by Boos4721** [comment]
> Do you have any plans to push it upstream? I can see that in OpenWrt, there is a 5.10.83 version. It would be nice to have it there as well.
> 
> I see there is a pending pull request for it: [openwrt/openwrt#4811](https://github.com/openwrt/openwrt/pull/4811)
> 
> Can you add there your `Tested-by` and on which platform(s) did you compile it and run tested it?

kk， ipq807x
iShot2021-12-16 09 45 35

**Comment by BKPepe** [comment]
@Boos4721 Ok, we have it here, but can you post it to upstream as well, please?

**Comment by Boos4721** [comment]
> @Boos4721 Ok, we have it here, but can you post it to upstream as well, please?

next time.

**Comment by BKPepe** [comment]
No, there is a pending pull request and upstream with the same kernel bump. So, it would be nice if you can do it right now.

**Comment by Boos4721** [comment]
> No, there is a pending pull request and upstream with the same kernel bump. So, it would be nice if you can do it right now.

Na, upstream havent add ipq807x and ipq60xx support, so i refresh kernel version by myself.

**Pull request merged**
