### PR TITLE
Revert "uboot-rockchip: fix nanopi-r2s failed to boot on some sd cards"

### LINKED ISSUE #5643: 使用 lede 源码编译 R2S ，不开机
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：使用 lede 源码给 R2S 编译 固件，make menuconfig 选择步骤是  rockchip ——rockchip_armv8 ——friendlyarm_nanopi-r2s  

然后步骤是make -j8 download V=s  -----make -j1 V=s ，操作步骤完全按照 lean 的指示来的， 固件编译成功，多次刷机无法进入系统，R2S 灯不亮，换别人的固件就可以

### (2) 路由器型号和固件版本

A：R2S  rk3328

### (3) 详细日志

A：R2S 灯不亮  无任何反应

### PR DESCRIPTION
**Pull request by AmadeusGhost**
This commit is duplicated with 8b42331 "rockchip: refresh NanoPi R2S
patches", so remove it to avoid startup problems, fix #5643

### CODE REVIEW

**Comment by 1715173329** [comment]
Not duplicated.
This is for uboot but not kernel.

**Comment by AmadeusGhost** [comment]
If it is not duplicate, the problem seems to be even bigger, the variable is not declared here.
And in these issues, someone said that the problem was solved after removing this patch.
```
diff --git a/package/boot/uboot-rockchip/src/of-platdata/nanopi-r2s-rk3328/dt-platdata.c b/package/boot/uboot-rockchip/src/of-platdata/nanopi-r2s-rk3328/dt-platdata.c
index fa42c1a760..a7c57e72c2 100644
--- a/package/boot/uboot-rockchip/src/of-platdata/nanopi-r2s-rk3328/dt-platdata.c
+++ b/package/boot/uboot-rockchip/src/of-platdata/nanopi-r2s-rk3328/dt-platdata.c
@@ -19,7 +19,7 @@ U_BOOT_DEVICE(syscon_at_ff100000) = {
 
 static const struct dtd_rockchip_rk3328_cru dtv_clock_controller_at_ff440000 = {
 	.reg			= {0xff440000, 0x1000},
-	.rockchip_grf		= 0x3a,
+	.rockchip_grf		= 0x3b,
 };
 U_BOOT_DEVICE(clock_controller_at_ff440000) = {
 	.name		= "rockchip_rk3328_cru",
@@ -49,7 +49,6 @@ U_BOOT_DEVICE(serial_at_ff130000) = {
 
 static const struct dtd_rockchip_rk3328_dw_mshc dtv_mmc_at_ff500000 = {
 	.bus_width		= 0x4,
-	.cap_mmc_highspeed	= true,
 	.cap_sd_highspeed	= true,
 	.clocks			= {
 			{&dtv_clock_controller_at_ff440000, {317}},
@@ -60,11 +59,15 @@ static const struct dtd_rockchip_rk3328_dw_mshc dtv_mmc_at_ff500000 = {
 	.fifo_depth		= 0x100,
 	.interrupts		= {0x0, 0xc, 0x4},
 	.max_frequency		= 0x8f0d180,
-	.pinctrl_0		= {0x47, 0x48, 0x49, 0x4a},
+	.pinctrl_0		= {0x48, 0x49, 0x4a, 0x4b},
 	.pinctrl_names		= "default",
 	.reg			= {0xff500000, 0x4000},
+	.sd_uhs_sdr104		= true,
+	.sd_uhs_sdr12		= true,
+	.sd_uhs_sdr25		= true,
+	.sd_uhs_sdr50		= true,
 	.u_boot_spl_fifo_mode	= true,
-	.vmmc_supply		= 0x4b,
+	.vmmc_supply		= 0x4c,
 	.vqmmc_supply		= 0x1e,
 };
 U_BOOT_DEVICE(mmc_at_ff500000) = {
@@ -75,7 +78,7 @@ U_BOOT_DEVICE(mmc_at_ff500000) = {
 
 static const struct dtd_rockchip_rk3328_pinctrl dtv_pinctrl = {
 	.ranges			= true,
-	.rockchip_grf		= 0x3a,
+	.rockchip_grf		= 0x3b,
 };
 U_BOOT_DEVICE(pinctrl) = {
 	.name		= "rockchip_rk3328_pinctrl",
@@ -98,9 +101,10 @@ U_BOOT_DEVICE(gpio0_at_ff210000) = {
 };
 
 static const struct dtd_regulator_fixed dtv_sdmmc_regulator = {
-	.gpio			= {0x60, 0x1e, 0x1},
-	.pinctrl_0		= 0x61,
+	.gpio			= {0x61, 0x1e, 0x1},
+	.pinctrl_0		= 0x68,
 	.pinctrl_names		= "default",
+	.regulator_boot_on	= true,
 	.regulator_max_microvolt = 0x325aa0,
 	.regulator_min_microvolt = 0x325aa0,
 	.regulator_name		= "vcc_sd",
diff --git a/package/boot/uboot-rockchip/src/of-platdata/nanopi-r2s-rk3328/dt-structs-gen.h b/package/boot/uboot-rockchip/src/of-platdata/nanopi-r2s-rk3328/dt-structs-gen.h
index 88291627b8..499ddb78a4 100644
--- a/package/boot/uboot-rockchip/src/of-platdata/nanopi-r2s-rk3328/dt-structs-gen.h
+++ b/package/boot/uboot-rockchip/src/of-platdata/nanopi-r2s-rk3328/dt-structs-gen.h
@@ -10,6 +10,7 @@ struct dtd_regulator_fixed {
 	fdt32_t		gpio[3];
 	fdt32_t		pinctrl_0;
 	const char *	pinctrl_names;
+	bool		regulator_boot_on;
 	fdt32_t		regulator_max_microvolt;
 	fdt32_t		regulator_min_microvolt;
 	const char *	regulator_name;
@@ -32,7 +33,6 @@ struct dtd_rockchip_rk3328_dmc {
 };
 struct dtd_rockchip_rk3328_dw_mshc {
 	fdt32_t		bus_width;
-	bool		cap_mmc_highspeed;
 	bool		cap_sd_highspeed;
 	struct phandle_1_arg clocks[4];
 	bool		disable_wp;
@@ -42,6 +42,10 @@ struct dtd_rockchip_rk3328_dw_mshc {
 	fdt32_t		pinctrl_0[4];
 	const char *	pinctrl_names;
 	fdt64_t		reg[2];
+	bool		sd_uhs_sdr104;
+	bool		sd_uhs_sdr12;
+	bool		sd_uhs_sdr25;
+	bool		sd_uhs_sdr50;
 	bool		u_boot_spl_fifo_mode;
 	fdt32_t		vmmc_supply;
 	fdt32_t		vqmmc_supply;
```

**Comment by 1715173329** [comment]
See openwrt/openwrt#3277, this has been verified as a vaild patch for resolving the issue.
The vars will not take such a effect and never mind.

**Comment by AmadeusGhost** [comment]
See https://github.com/openwrt/openwrt/pull/3367#issuecomment-700501744 , I don’t think it’s correct to put this patch on uboot.

**Comment by 1715173329** [comment]
Actually you may see there's much difference in DTS between uboot and kernel, they work independently.

BTW, upstream has made a [new change](https://git.openwrt.org/?p=openwrt/staging/blocktrron.git;a=commitdiff;h=fb6ee0c112a4b707eaaa1d0d6154f936173fc63a) for uboot, I would like to carry that then and remove this patch as it was included in the former already.

**Comment by 1715173329** [comment]
> I don’t think it’s correct to put this patch on uboot.

It's correct, see last:
> Also I see that uboot patch has included master branch.

Unfortunately this was reverted as it will break ethernet on-board, so we need reintroduce the patch until the commit I referred is being merged.

**Comment by AmadeusGhost** [comment]
> The vars will not take such a effect and never mind.

Call failure sometimes may causes wrong results to be returned. Since someone removed this patch and solved the problem, why not do it first? The upstream patches still need further testing, and I have no time to test these.

**Comment by 1715173329** [comment]
> Call failure sometimes may causes wrong results to be returned.

We've ever made lots of tries on the patch (yes at least hundreds of users joined the test) and everything was worked as except.

**Comment by 1715173329** [comment]
And I don't wanna fix an exception but break the experience for most users, as you may know the shit workmanship from FriendlyElec causes R2S failed to boot on many SD cards.

**Comment by AmadeusGhost** [comment]
I don’t understand this very well. At that time, the code of the kernel and uboot were different.
It seems that if there is no declaration that this variable will return any value.

**Pull request closed without merging**
