### PR TITLE
shortcut-fe:update

### PR DESCRIPTION
**Pull request by Ailick**
Q：你知道这是`pull request`吗？(使用 "x" 选择)
* [ ] 我知道
==更新shortcut-fe全家桶到2021-03-17，HEAD=697977d8d0ccf0ab596e5692d08608a75dd7f33d
-> 内核：导出udp_get_timeouts
-> FAST Classifier & CM：
--- IPSec禁用SFE
--- 可与ECM同时启动**（CM与Simulated同时启动可能不稳定，待测试）**
-> Shortcut-FE：
--- 禁用模块自启动，启动方式受脚本控制
--- 启动脚本配合ECM（有ECM存在时，将接管SFE的启动）
-> luci-app-turboacc :
---使用SFE-CM作为默认消息管理
---806x/807x 使用ECM时默认勾选Simulated Sfe-Drv
==（感谢狂风大佬的模板和尘毒大佬的分享）

### CODE REVIEW

**Comment by Boos4721** [comment]
`/openwrt/target/linux/ipq807x/patches-5.10/601-netfilter-export-udp_get_timeouts-function.patch using plaintext: 
patching file include/net/netfilter/nf_conntrack_timeout.h
Hunk #1 FAILED at 123.
1 out of 1 hunk FAILED -- saving rejects to file include/net/netfilter/nf_conntrack_timeout.h.rej
patching file net/netfilter/nf_conntrack_proto_udp.c
Hunk #1 FAILED at 29.
1 out of 1 hunk FAILED -- saving rejects to file net/netfilter/nf_conntrack_proto_udp.c.rej`
[和这个冲突了啊](https://github.com/coolsnowwolf/lede/pull/7817/files#diff-3125e48f36ee520152c93ced859ce970139412943f6d366a6b1cee79c437b6c2)

**Comment by Ailick** [comment]
> `/openwrt/target/linux/ipq807x/patches-5.10/601-netfilter-export-udp_get_timeouts-function.patch using plaintext: patching file include/net/netfilter/nf_conntrack_timeout.h Hunk #1 FAILED at 123. 1 out of 1 hunk FAILED -- saving rejects to file include/net/netfilter/nf_conntrack_timeout.h.rej patching file net/netfilter/nf_conntrack_proto_udp.c Hunk #1 FAILED at 29. 1 out of 1 hunk FAILED -- saving rejects to file net/netfilter/nf_conntrack_proto_udp.c.rej`
> [和这个冲突了啊](https://github.com/coolsnowwolf/lede/pull/7817/files#diff-3125e48f36ee520152c93ced859ce970139412943f6d366a6b1cee79c437b6c2)

删除601-netfilter-export-udp_get_timeouts-function.patch即可

**Comment by Boos4721** [comment]
> > `/openwrt/target/linux/ipq807x/patches-5.10/601-netfilter-export-udp_get_timeouts-function.patch using plaintext: patching file include/net/netfilter/nf_conntrack_timeout.h Hunk #1 FAILED at 123. 1 out of 1 hunk FAILED -- saving rejects to file include/net/netfilter/nf_conntrack_timeout.h.rej patching file net/netfilter/nf_conntrack_proto_udp.c Hunk #1 FAILED at 29. 1 out of 1 hunk FAILED -- saving rejects to file net/netfilter/nf_conntrack_proto_udp.c.rej`
> > [和这个冲突了啊](https://github.com/coolsnowwolf/lede/pull/7817/files#diff-3125e48f36ee520152c93ced859ce970139412943f6d366a6b1cee79c437b6c2)
> 
> 删除601-netfilter-export-udp_get_timeouts-function.patch即可

我知道 你pr里面不加么👀

**Comment by Ailick** [comment]
> > > `/openwrt/target/linux/ipq807x/patches-5.10/601-netfilter-export-udp_get_timeouts-function.patch using plaintext: patching file include/net/netfilter/nf_conntrack_timeout.h Hunk #1 FAILED at 123. 1 out of 1 hunk FAILED -- saving rejects to file include/net/netfilter/nf_conntrack_timeout.h.rej patching file net/netfilter/nf_conntrack_proto_udp.c Hunk #1 FAILED at 29. 1 out of 1 hunk FAILED -- saving rejects to file net/netfilter/nf_conntrack_proto_udp.c.rej`
> > > [和这个冲突了啊](https://github.com/coolsnowwolf/lede/pull/7817/files#diff-3125e48f36ee520152c93ced859ce970139412943f6d366a6b1cee79c437b6c2)
> > 
> > 
> > 删除601-netfilter-export-udp_get_timeouts-function.patch即可
> 
> 我知道 你pr里面不加么👀

主要是远程分支的commit我覆盖不了，改来改去提交太多，要是没别的问题，就等lean来处理吧

**Comment by Boos4721** [comment]
> > > > `/openwrt/target/linux/ipq807x/patches-5.10/601-netfilter-export-udp_get_timeouts-function.patch using plaintext: patching file include/net/netfilter/nf_conntrack_timeout.h Hunk #1 FAILED at 123. 1 out of 1 hunk FAILED -- saving rejects to file include/net/netfilter/nf_conntrack_timeout.h.rej patching file net/netfilter/nf_conntrack_proto_udp.c Hunk #1 FAILED at 29. 1 out of 1 hunk FAILED -- saving rejects to file net/netfilter/nf_conntrack_proto_udp.c.rej`
> > > > [和这个冲突了啊](https://github.com/coolsnowwolf/lede/pull/7817/files#diff-3125e48f36ee520152c93ced859ce970139412943f6d366a6b1cee79c437b6c2)
> > > 
> > > 
> > > 删除601-netfilter-export-udp_get_timeouts-function.patch即可
> > 
> > 
> > 我知道 你pr里面不加么👀
> 
> 主要是远程分支的commit我覆盖不了，改来改去提交太多，要是没别的问题，就等lean来处理吧

可

**Comment by Boos4721** [comment]
[kernel panic了](https://netcut.cn/1fet6gutb)

**Comment by Ailick** [comment]
> [kernel panic了](https://netcut.cn/1fet6gutb)

我晚点测试ecm，看看具体问题

**Comment by Boos4721** [comment]
> > [kernel panic了](https://netcut.cn/1fet6gutb)
> 
> 我晚点测试ecm，看看具体问题

行吧

**Comment by Ailick** [comment]
> > > [kernel panic了](https://netcut.cn/1fet6gutb)
> > 
> > 
> > 我晚点测试ecm，看看具体问题
> 
> 行吧



> > > [kernel panic了](https://netcut.cn/1fet6gutb)
> > 
> > 
> > 我晚点测试ecm，看看具体问题
> 
> 行吧

luci-app-turboacc按默认选择，试试

**Comment by Boos4721** [comment]
> > > > [kernel panic了](https://netcut.cn/1fet6gutb)
> > > 
> > > 
> > > 我晚点测试ecm，看看具体问题
> > 
> > 
> > 行吧
> 
> > > > [kernel panic了](https://netcut.cn/1fet6gutb)
> > > 
> > > 
> > > 我晚点测试ecm，看看具体问题
> > 
> > 
> > 行吧
> 
> luci-app-turboacc按默认选择，试试

默认是不勾sfe的

**Comment by Ailick** [comment]
> > > > > [kernel panic了](https://netcut.cn/1fet6gutb)
> > > > 
> > > > 
> > > > 我晚点测试ecm，看看具体问题
> > > 
> > > 
> > > 行吧
> > 
> > 
> > > > > [kernel panic了](https://netcut.cn/1fet6gutb)
> > > > 
> > > > 
> > > > 我晚点测试ecm，看看具体问题
> > > 
> > > 
> > > 行吧
> > 
> > 
> > luci-app-turboacc按默认选择，试试
> 
> 默认是不勾sfe的

默认的是对的，有sfe-ecm就够了

**Comment by Boos4721** [comment]
> > > > > > [kernel panic了](https://netcut.cn/1fet6gutb)
> > > > > 
> > > > > 
> > > > > 我晚点测试ecm，看看具体问题
> > > > 
> > > > 
> > > > 行吧
> > > 
> > > 
> > > > > > [kernel panic了](https://netcut.cn/1fet6gutb)
> > > > > 
> > > > > 
> > > > > 我晚点测试ecm，看看具体问题
> > > > 
> > > > 
> > > > 行吧
> > > 
> > > 
> > > luci-app-turboacc按默认选择，试试
> > 
> > 
> > 默认是不勾sfe的
> 
> 默认的是对的，有sfe-ecm就够了

> Include Shortcut-FE with ECM

**Comment by Ailick** [comment]
> > > > > > > [kernel panic了](https://netcut.cn/1fet6gutb)
> > > > > > 
> > > > > > 
> > > > > > 我晚点测试ecm，看看具体问题
> > > > > 
> > > > > 
> > > > > 行吧
> > > > 
> > > > 
> > > > > > > [kernel panic了](https://netcut.cn/1fet6gutb)
> > > > > > 
> > > > > > 
> > > > > > 我晚点测试ecm，看看具体问题
> > > > > 
> > > > > 
> > > > > 行吧
> > > > 
> > > > 
> > > > luci-app-turboacc按默认选择，试试
> > > 
> > > 
> > > 默认是不勾sfe的
> > 
> > 
> > 默认的是对的，有sfe-ecm就够了
> 
> > Include Shortcut-FE with ECM

是的

**Comment by Boos4721** [comment]
[还是一样的](https://images.weserv.nl/?url=https://i0.hdslb.com/bfs/album/5189507761fb53456096ede73fef2eb104f7ebff.jpg)

**Comment by Boos4721** [comment]
> [还是一样的](https://images.weserv.nl/?url=https://i0.hdslb.com/bfs/album/5189507761fb53456096ede73fef2eb104f7ebff.jpg)

`# CONFIG_PACKAGE_TURBOACC_INCLUDE_OFFLOADING is not set
# CONFIG_PACKAGE_TURBOACC_INCLUDE_SHORTCUT_FE is not set
CONFIG_PACKAGE_TURBOACC_INCLUDE_BBR_CCA=y
CONFIG_PACKAGE_TURBOACC_INCLUDE_DNSFORWARDER=y
# CONFIG_PACKAGE_TURBOACC_INCLUDE_DNSPROXY is not set
CONFIG_PACKAGE_TURBOACC_INCLUDE_ECM_SFE=y`

**Comment by Ailick** [comment]
> > [还是一样的](https://images.weserv.nl/?url=https://i0.hdslb.com/bfs/album/5189507761fb53456096ede73fef2eb104f7ebff.jpg)
> 
> `# CONFIG_PACKAGE_TURBOACC_INCLUDE_OFFLOADING is not set`
> `# CONFIG_PACKAGE_TURBOACC_INCLUDE_SHORTCUT_FE is not set`
> `CONFIG_PACKAGE_TURBOACC_INCLUDE_BBR_CCA=y`
> `CONFIG_PACKAGE_TURBOACC_INCLUDE_DNSFORWARDER=y`
> `# CONFIG_PACKAGE_TURBOACC_INCLUDE_DNSPROXY is not set`
> `CONFIG_PACKAGE_TURBOACC_INCLUDE_ECM_SFE=y`

检查kmod-shortcut-fe-cm，这个不需要选中

**Comment by Boos4721** [comment]
> kmod-shortcut-fe-cm

humm让我试试

**Comment by Boos4721** [comment]
可以了807x nss的udp也工作了

**Pull request closed without merging**
