### PR TITLE
dnsproxy: move package feeds

### PR DESCRIPTION
**Pull request by Beginner-Go**

### CODE REVIEW

**Comment by BKPepe** [comment]
This one should be cherry-picked from upstream: https://github.com/openwrt/packages/commit/5f1e6f7d09c5f0046877677ca0a50ce559426415.

So the authorship remains the same for the author.

**Comment by Beginner-Go** [comment]
Ok i will correct it.

**Comment by AmadeusGhost** [comment]
Can these packages moving to package feeds?

**Comment by Beginner-Go** [comment]
> Can these packages moving to [package feeds](https://github.com/coolsnowwolf/packages)?

Ok i will do it.

**Pull request merged**
