### PR TITLE
CI: rm useless apt sources

### PR DESCRIPTION
**Pull request by KFERMercer**
- 修复近期多发的因巨硬土豆集群发芽导致的流程失败
- 多线程编译失败时自动切换为单线程
- 由于难以匹配几亿种不同的固件格式和命名格式, 放弃只上传固件
- 删除定制模板部分以改进代码可读性
- 同步最近更改

### CODE REVIEW

**Comment by Ryuchen** [comment]
then how to set my custom settings?

**Comment by KFERMercer** [comment]
> then how to set my custom settings?

https://raw.githubusercontent.com/KFERMercer/OpenWrt-CI/master/openwrt-ci.yml

**Comment by Ryuchen** [comment]
> > then how to set my custom settings?
> 
> [KFERMercer/OpenWrt-CI:openwrt-ci.yml@`master` (raw)](https://raw.githubusercontent.com/KFERMercer/OpenWrt-CI/master/openwrt-ci.yml)

But your pull request remove the Generate configuration file section in this repo about the github action, would you please check your pull request?

https://github.com/coolsnowwolf/lede/blob/master/.github/workflows/openwrt-ci.yml

**Comment by KFERMercer** [comment]
yea, it's true. because coolsnowwolf dont need the custom section.

**Comment by luk24** [comment]
> yea, it's true. because coolsnowwolf dont need the custom section.

机型定制部分也不需要了？这编译出来的固件是通用固件？

**Pull request merged**
