### PR TITLE
kernel: `5.15` refresh patches

### PR DESCRIPTION
**Pull request by Beginner-Go**

### CODE REVIEW

**Comment by aiamadeus** [comment]
参考下这个 commit，不要整个 patch 直接删掉 https://github.com/coolsnowwolf/lede/commit/65d8795b3d9e1c40f4c922aa1cd87e59cb63826e
你把 5.10 5.15 分开 pr 的话我可以先合并一个

**Comment by Beginner-Go** [comment]
okey.

**Comment by aiamadeus** [comment]
https://github.com/openwrt/openwrt/blob/main/target/linux/ath79/patches-5.15/900-unaligned_access_hacks.patch 
这个补丁还在

**Comment by Beginner-Go** [comment]
[lean 添加了](https://github.com/coolsnowwolf/lede/commit/67dcd386785ccb76136d6548f075422fceff3b7a#diff-b08322af4b079a146e1a6abd8d083ceb43b25607449402f9ab756fdaeba193cd)

**Pull request closed without merging**
