### PR TITLE
Revert "v2ray-plugin: update to 4.37.3"

### PR DESCRIPTION
**Pull request by Beginner-Go**
https://github.com/coolsnowwolf/lede/issues/6693

### CODE REVIEW

**Comment by AmadeusGhost** [comment]
没必要 revert 吧，把那个 patch 打上就行

**Comment by Beginner-Go** [comment]
> 没必要 revert 吧，把那个 patch 打上就行

已和 v2ray-plugin(秋水大佬) 作者沟通，他建议我回退

**Comment by Dimitri2020007** [comment]
这个可以根据之前的校验和记录修改make文件回退到上个版本吗？

**Comment by EnnawYang** [comment]
> 这个可以根据之前的校验和记录修改make文件回退到上个版本吗？

可

**Comment by Dimitri2020007** [comment]
我已经修改了v2ray-plugin的版本和校验和，现在再跑一遍github actions试下看行不行。

**Comment by vodott** [comment]
还是不行。

go: downloading github.com/v2fly/v2ray-core/v4 v4.37.3
8833
verifying ***@***.***: checksum mismatch
8834
	downloaded: h1:FGmf5rtUo3xGHyZGJi8jEa7AKin05ROfPtegmGbkCKg=
8835
	go.sum:     h1:Kf9Qot2lLYccEzQfoCdt9img6zo5Vf+PEaoTMfa2S8k=
8836

8837
SECURITY ERROR
8838
This download does NOT match an earlier download recorded in go.sum.
8839
The bits may have been replaced on the origin server, or an attacker may
8840
have intercepted the download attempt.
8841

8842
For more information, see 'go help module-auth'.

**Comment by Dimitri2020007** [comment]
> 还是不行。 go: downloading github.com/v2fly/v2ray-core/v4 v4.37.3 8833 verifying ***@***.***: checksum mismatch 8834 downloaded: h1:FGmf5rtUo3xGHyZGJi8jEa7AKin05ROfPtegmGbkCKg= 8835 go.sum: h1:Kf9Qot2lLYccEzQfoCdt9img6zo5Vf+PEaoTMfa2S8k= 8836 8837 SECURITY ERROR 8838 This download does NOT match an earlier download recorded in go.sum. 8839 The bits may have been replaced on the origin server, or an attacker may 8840 have intercepted the download attempt. 8841 8842 For more information, see 'go help module-auth'.
> […](#)
> 在 2021年4月16日，12:34，Dimitri2020007 ***@***.***> 写道： ﻿ 我已经修改了v2ray-plugin的版本和校验和，现在再跑一遍github actions试下看行不行。 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

若fo了这个源码请修改这个文件Makefile

位置在package/lean/v2ray-plugin/Makefile

修改第11行和第16行的内容

11行改版本为PKG_VERSION:=4.37.2

16行改校验和为PKG_HASH:=e776a2294dba5dbf832dc5ea673ffbb66ae6fac54df90ff286a5d1833a4ae874

改过以后再编译下试试

**Pull request merged**
