### PR TITLE
kernel: bump 5.4 to 5.4.118

### PR DESCRIPTION
**Pull request by Boos4721**
Signed-off-by: Boos4721 <3.1415926535boos@gmail.com>

Q：你知道这是`pull request`吗？(使用 "x" 选择)
* [x] 我知道

### CODE REVIEW

**Comment by Beginner-Go** [comment]
你能编译成功算我输

**Comment by Beginner-Go** [comment]
Closed

**Comment by Boos4721** [comment]
`Kernel Version Ss`
[https://www.hualigs.cn/image/609c0b9c73676.jpg](url)

**Comment by Beginner-Go** [comment]
patch not update ?

**Comment by Boos4721** [comment]
> patch not update ?

https://git.openwrt.org/?p=openwrt/openwrt.git;a=commit;h=da16b801a32a53ba4315d8cc67b7ac0deb7ff4c0

**Comment by Boos4721** [comment]
> patch not update ?

https://github.com/coolsnowwolf/lede/commit/28456ea99335916c670901569831692c04b96909
https://git.openwrt.org/?p=openwrt/openwrt.git;a=commit;h=da16b801a32a53ba4315d8cc67b7ac0deb7ff4c0
same to u

**Comment by Beginner-Go** [comment]
It all depends

**Comment by Beginner-Go** [comment]
why closed ? https://github.com/coolsnowwolf/lede/pull/6819

**Comment by Boos4721** [comment]
> why closed ? #6819

some error

**Pull request closed without merging**
