### PR TITLE
增加NFS服务控制台

### PR DESCRIPTION
**Pull request by Aes64X**
Q：你知道这是`pull request`吗？(使用 "x" 选择)
* [yep~ ] 我知道

初始提交是: springsunx  感谢他的工作

已带有依赖关联，已测试本地存储挂载共享正常，还有个挂在远程目录没测试。

通过测试的机型：Newifi D1、竞斗云、EA4500、R3G、K3

此处强烈推荐NFS共享+EXT4啊啊啊啊啊，兼容性俱佳啊啊啊啊啊啊

### CODE REVIEW

**Comment by hue715** [comment]
_Originally posted by @springsunx in https://github.com/coolsnowwolf/lede/issues/2957#issuecomment-586551033_

**Comment by Aes64X** [comment]
> _Originally posted by @springsunx in [#2957 (comment)](https://github.com/coolsnowwolf/lede/issues/2957#issuecomment-586551033)_

thk

**Comment by hue715** [comment]
> > _Originally posted by @springsunx in [#2957 (comment)](https://github.com/coolsnowwolf/lede/issues/2957#issuecomment-586551033)_
> 
> thk

后来又有了更新，不知有哪些变化
_Originally posted by @springsunx in https://github.com/coolsnowwolf/lede/pull/3073#issuecomment-586556106_

**Comment by Aes64X** [comment]
> > > _Originally posted by @springsunx in [#2957 (comment)](https://github.com/coolsnowwolf/lede/issues/2957#issuecomment-586551033)_
> > 
> > 
> > thk
> 
> 后来又有了更新，不知有哪些变化
> _Originally posted by @springsunx in [#3073 (comment)](https://github.com/coolsnowwolf/lede/pull/3073#issuecomment-586556106)_

容我再测试一波。。。。

**Comment by hue715** [comment]
> > > > _Originally posted by @springsunx in [#2957 (comment)](https://github.com/coolsnowwolf/lede/issues/2957#issuecomment-586551033)_
> > > 
> > > 
> > > thk
> > 
> > 后来又有了更新，不知有哪些变化
> > _Originally posted by @springsunx in [#3073 (comment)](https://github.com/coolsnowwolf/lede/pull/3073#issuecomment-586556106)_
> 
> 容我再测试一波。。。。

😂版本号是一致的，可能是同一个包。

**Comment by Aes64X** [comment]
> > > > > _Originally posted by @springsunx in [#2957 (comment)](https://github.com/coolsnowwolf/lede/issues/2957#issuecomment-586551033)_
> > > > 
> > > > 
> > > > thk
> > > 
> > > 
> > > 后来又有了更新，不知有哪些变化
> > > _Originally posted by @springsunx in [#3073 (comment)](https://github.com/coolsnowwolf/lede/pull/3073#issuecomment-586556106)_
> > 
> > 
> > 容我再测试一波。。。。
> 
> 😂版本号是一致的，可能是同一个包。

是同一个，只是init.d/nfs 的权限改变了

package/lean/luci-app-nfs/root/etc/init.d/nfs  100755 → 100644

**Pull request merged**
