### PR TITLE
kernel: bump to 4.9.208, 4.14.162, 4.19.93

### PR DESCRIPTION
**Pull request by AmadeusGhost**
1. update mdadm to latest version, fix issue #2751
2. fix syntax errors exposed after kconfig update
3. revert add support for mtd-mac-address-ascii in device-tree, this change have problems in some platforms.

### CODE REVIEW

**Comment by bzzjh** [comment]
更新了代码：重新编译出错了

**Comment by AmadeusGhost** [comment]
回退了还出错？

**Comment by bzzjh** [comment]
今天刚刚更新了git pull,然后make clean,重新编译，到这里就出错了，好像跟read_mtd_mac_address相关的patch有关吧？

**Comment by AmadeusGhost** [comment]
照着这个pr改回去呢？

**Comment by bzzjh** [comment]
好的，多谢，辛苦了，我再尝试

**Comment by bzzjh** [comment]
再次更新了源代码，已经编译过去了，刚才出错的地方

AR      drivers/nvme/built-in.o
  CC      drivers/of/base.o
  CC      drivers/of/device.o
  CC      drivers/of/platform.o
  CC      drivers/of/property.o
  CC      drivers/of/fdt.o
  CC      drivers/of/fdt_address.o
  CC      drivers/of/address.o
  CC      drivers/of/irq.o
  **CC      drivers/of/of_net.o**
  CC      drivers/of/of_pci.o
  CC      drivers/of/of_pci_irq.o
  CC      drivers/of/of_reserved_mem.o
  AR      drivers/of/built-in.o
  CC      drivers/pci/access.o
  CC      drivers/pci/bus.o

**Pull request merged**
