### PR TITLE
luci-app-ssr-plus: use "&" to instead of "-d" (daemon mode)

### PR DESCRIPTION
**Pull request by 1715173329**

### CODE REVIEW

**Comment by Mattraks** [comment]
意义何在？

**Comment by 1715173329** [comment]
Running in daemon mode may cause the error "tcp/udp: socket/address already in use", even there's no software listen on the port.
If we use "&" (running in background), and this error will no longer appear.
I don't know how does this happend.

**Comment by lonelysoul** [comment]
支持一个
目前，在启用双节点（主节点美国、Netflix香港）的情况下，启用socks5代理，系统日志就会报这个错误，ssrp重启；

**Comment by lonelysoul** [comment]
支持一个

**Comment by 1715173329** [comment]
Besides, this resolves the error, no just redirect the error log to null.
(Actually if the error remains, it's totally improssible to run.)

I just hope it will work asap, that's it.

**Comment by qq1316237299** [comment]
支持下大佬

**Comment by ckxt** [comment]
谢谢大佬，我确实碰到了这个问题！！！

**Pull request merged**
